services:
  - type: web
    name: tomato-disease-classifier
    runtime: python
    pythonVersion: 3.11
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
